// <auto-generated />
namespace Crud_Login_Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class abcmig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abcmig));
        
        string IMigrationMetadata.Id
        {
            get { return "202403071211428_abc-mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
